name: homestay_booking
description: A cross-platform homestay booking management application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  provider: ^6.0.5

  # UI components
  table_calendar: ^3.0.9
  syncfusion_flutter_datepicker: ^22.1.34
  intl: ^0.18.0
  cupertino_icons: ^1.0.5

  # Data persistence
  sqflite: ^2.2.8+4
  path: ^1.8.3
  flutter_secure_storage: ^8.0.0

  # Networking
  http: ^0.13.6

  # Utilities
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  build_runner: ^2.3.3
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
