// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO8xxRSFMWCDq65WvO_QX66WR3Mmz_Xk4',
    appId: '1:371806807289:web:65df9fd81ae55be3e22e28',
    messagingSenderId: '371806807289',
    projectId: 'idaman-homestay',
    authDomain: 'idaman-homestay.firebaseapp.com',
    storageBucket: 'idaman-homestay.firebasestorage.app',
    measurementId: 'G-Q5L8F2WGSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTCGZIUDY48THB7ykD93Miku7E7j8y-s',
    appId: '1:371806807289:android:65a18b70a6b9876ce22e28',
    messagingSenderId: '371806807289',
    projectId: 'idaman-homestay',
    storageBucket: 'idaman-homestay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuVzYOXZMYv6SkoWSwgUreaPWJoI3UDXE',
    appId: '1:371806807289:ios:5b4052e48961863be22e28',
    messagingSenderId: '371806807289',
    projectId: 'idaman-homestay',
    storageBucket: 'idaman-homestay.firebasestorage.app',
    iosBundleId: 'com.example.channelManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO8xxRSFMWCDq65WvO_QX66WR3Mmz_Xk4',
    appId: '1:371806807289:web:0380a626e47c2712e22e28',
    messagingSenderId: '371806807289',
    projectId: 'idaman-homestay',
    authDomain: 'idaman-homestay.firebaseapp.com',
    storageBucket: 'idaman-homestay.firebasestorage.app',
    measurementId: 'G-CTS5WY4LMV',
  );

}